// Generated by CoffeeScript 1.5.0
var routes;

global.controls = require('./public/js/controls');

global.dbsettings = require('./conf/database.json');

global.appsettings = require('./settings/sms.json');

routes = require('./public/js/routes');

routes.index();
